DACN/Controllers/BenhNhanController.cs
using DACN.Models;
using DACN.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace DACN.Controllers
{
    public class BenhNhanController : Controller
    {
        private DACNDBContext db = new DACNDBContext();

        //DS Bệnh Nhân
        public ActionResult TaiKhoanBN()
        {
            return View(db.BenhNhans.ToList());
        }

        //Chi Tiết Bệnh Nhân
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BenhNhan bn = db.BenhNhans.Find(id);
            if (bn == null)
            {
                return HttpNotFound();
            }
            return View(bn);
        }

        //Tạo tài khoản Bệnh Nhân
        public ActionResult Create()
        {
            ViewBag.MaGioiTinh = new SelectList(db.GioiTinhs, "MaGioiTinh", "TenGioiTinh");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BNViewModel model)
        {
            try
            {
                if (model.avatarFile != null && model.avatarFile.ContentLength > 0)
                {
                    string subPath = Server.MapPath("~/Content/HinhAnh/AvtBN/");
                    bool exists = System.IO.Directory.Exists(subPath);
                    if (!exists)
                    {
                        System.IO.Directory.CreateDirectory(subPath);
                    }
                    string extension = Path.GetExtension(model.avatarFile.FileName);
                    model.HinhAnh = model.avatarFile.FileName;
                    model.avatarFile.SaveAs(Server.MapPath("~/Content/HinhAnh/AvtBN/") + model.HinhAnh);
                }
            }
            catch (Exception) { }
            BenhNhan bn = new BenhNhan
            {
                HinhAnh = model.HinhAnh,
                TaiKhoan = model.TaiKhoan,
                MatKhau = model.MatKhau,
                HoVaTen = model.HoVaTen,
                NgaySinh = model.NgaySinh,
                MaGioiTinh = model.MaGioiTinh,
                SDT = model.SDT,
                Email = model.Email,
                TrangThai = 1
            };
            var check = db.BenhNhans.FirstOrDefault(p => p.TaiKhoan == model.TaiKhoan);
            if (check == null)
            {
                db.BenhNhans.Add(bn);
                db.SaveChanges();
                SetAlert("Thêm tài khoản thành công", "success");
                return RedirectToAction("TaiKhoanBN");
            }
            else
            {
                SetAlert("Tên đăng nhập đã tồn tại", "error");
                return RedirectToAction("TaiKhoanBN");
            }
        }

        //Chỉnh Sửa Thông tin Bệnh Nhân
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BenhNhan bn = db.BenhNhans.Find(id);
            if (bn == null)
            {
                return HttpNotFound();
            }
            BNViewModel model = new BNViewModel
            {
                MaBenhNhan = bn.MaBenhNhan,
                HinhAnh = bn.HinhAnh,
                TaiKhoan = bn.TaiKhoan,
                MatKhau = bn.MatKhau,
                HoVaTen = bn.HoVaTen,
                NgaySinh = bn.NgaySinh,
                MaGioiTinh = bn.MaGioiTinh,
                SDT = bn.SDT,
                Email = bn.Email,
                TrangThai = bn.TrangThai
            };
            ViewBag.MaGioiTinh = new SelectList(db.GioiTinhs, "MaGioiTinh", "TenGioiTinh", bn.MaGioiTinh);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BNViewModel model)
        {
            BenhNhan bn = db.BenhNhans.Find(model.MaBenhNhan);
            if (model.avatarFile != null && model.avatarFile.ContentLength > 0)
            {
                string subPath = Server.MapPath("~/Content/HinhAnh/AvtBN/");
                bool exists = System.IO.Directory.Exists(subPath);
                if (!exists)
                {
                    System.IO.Directory.CreateDirectory(subPath);
                }
                model.HinhAnh = model.avatarFile.FileName;
                model.avatarFile.SaveAs(Server.MapPath("~/Content/HinhAnh/AvtBN/") + model.HinhAnh);
            }
            else
            {
                model.HinhAnh = bn.HinhAnh.ToString();
            }
            bn.MaBenhNhan = model.MaBenhNhan;
            bn.HinhAnh = model.HinhAnh;
            bn.TaiKhoan = model.TaiKhoan;
            bn.MatKhau = model.MatKhau;
            bn.HoVaTen = model.HoVaTen;
            bn.NgaySinh = model.NgaySinh;
            bn.MaGioiTinh = model.MaGioiTinh;
            bn.SDT = model.SDT;
            bn.Email = model.Email;
            bn.TrangThai = 1;
            db.Entry(bn).State = EntityState.Modified;
            db.SaveChanges();
            SetAlert("Chỉnh sửa thành công", "success");
            return RedirectToAction("TaiKhoanBN");
        }

        //Xóa Tài Khoản Bệnh Nhân
        [HttpDelete]
        public ActionResult Delete(int id)
        {
            BenhNhan bn = db.BenhNhans.Find(id);
            bn.TrangThai = 2;
            db.SaveChanges();
            return RedirectToAction("TaiKhoanBN");
        }

        //Thông Báo
        protected void SetAlert(string message, string type)
        {
            TempData["AlertMessage"] = message;
            if (type == "success")
            {
                TempData["AlertType"] = "alert-success";
            }
            else if (type == "warning")
            {
                TempData["AlertType"] = "alert-warning";
            }
            else if (type == "error")
            {
                TempData["AlertType"] = "alert-danger";
            }
        }
    }
}

DACN/Views/Shared/AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Admin</title>
    <link href="~/Public/layoutAdmin/css/styles.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>
</head>
@{
    var userAdmin = Session["userAdmin"] as DACN.Models.Admin;
}
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark badge-success">
        <a class="navbar-brand" href="@Url.Action("Index", "Admin")"><img src="~/Public/images/Health-Care-Logo-1.jpg" width="130" height="50" /></a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button><!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Từ khóa..." aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="@Url.Action("Dangxuat", "Admin")"> Đăng xuất</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        @{
                            if (userAdmin != null)
                            {
                                <div class="sb-sidenav-menu-heading" style="color:red">Xin chào: @userAdmin.TaiKhoan </div>

                            }
                            <div class="sb-sidenav-menu-heading">Trang chủ</div>
                        }
                        <a class="nav-link" href="@Url.Action("TrangQuanTri", "Admin")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Bảng thông tin
                        </a>
                        <div class="sb-sidenav-menu-heading"> <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>Quản lý chức năng</div>

                        <a class="nav-link" href="@Url.Action("DSTaiKhoan", "Admin")"> <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>Tài Khoản Quản Trị Viên</a>
                        <a class="nav-link" href="@Url.Action("TaiKhoanBS", "BacSi")"> <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>Tài Khoản Bác Sĩ</a>
                        <a class="nav-link" href="@Url.Action("TaiKhoanBN", "BenhNhan")"> <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>Tài Khoản Bệnh Nhân</a>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Quản lý danh mục
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="#"> Khác</a>
                                <a class="nav-link" href="#">Giao diện</a>
                            </nav>
                        </div>

                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Authentication
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav"><a class="nav-link" href="login.html">Login</a><a class="nav-link" href="register.html">Register</a><a class="nav-link" href="password.html">Forgot Password</a></nav>
                                </div>
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                    Error
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav"><a class="nav-link" href="401.html">401 Page</a><a class="nav-link" href="404.html">404 Page</a><a class="nav-link" href="500.html">500 Page</a></nav>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    @if (TempData["AlertMessage"] != null)
                    {
                        <div id="AlertBox" class="alert @TempData["AlertType"] hide">
                            @TempData["AlertMessage"]
                        </div>
                    }
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted"> CNTT-HDU &copy; 2020</div>
                        <div>
                            <a href="#"> Xem thêm</a>
                            &middot;
                            <a href="#">BlockChain &amp; ATTT</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Public/layoutAdmin/js/scripts.js"></script>
</body>
</html>

DACN/Views/Shared/Doctor_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <meta name="copyright" content="MACode ID, https://macodeid.com/">

    <title>One Health</title>
    <link href="~/Public/LayoutHome/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Public/LayoutHome/css/maicons.css" rel="stylesheet" />
    <link href="~//Public/LayoutHome/css/theme.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Public/LayoutHome/css/maicons.css">

    <link rel="stylesheet" href="~/Public/LayoutHome/css/bootstrap.css">

    <link rel="stylesheet" href="~/Public/LayoutHome/vendor/owl-carousel/css/owl.carousel.css">

    <link rel="stylesheet" href="~/Public/LayoutHome/vendor/animate/animate.css">

    <link rel="stylesheet" href="~/Public/LayoutHome/css/theme.css">
</head>
@{
    var userAdmin = Session["userAdmin"] as DACN.Models.BacSi;
}
<body>
    <!-- Back to top button -->
    <div class="back-to-top"></div>

    <header>
        <div class="topbar">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 text-sm">
                        <div class="site-info">
                            <a href="#"><span class="mai-call text-primary"></span> +84 090 480 4756</a>
                            <span class="divider">|</span>
                            <a href="#"><span class="mai-mail text-primary"></span> chamsocsuckhoe@temporary.net</a>
                        </div>
                    </div>
                    <div class="col-sm-4 text-right text-sm">
                        <div class="social-mini-button">
                            <a href="#"><span class="mai-logo-facebook-f"></span></a>
                            <a href="#"><span class="mai-logo-twitter"></span></a>
                            <a href="#"><span class="mai-logo-dribbble"></span></a>
                            <a href="#"><span class="mai-logo-instagram"></span></a>
                        </div>
                    </div>
                </div> <!-- .row -->
            </div> <!-- .container -->
        </div> <!-- .topbar -->

        <nav class="navbar navbar-expand-lg navbar-light shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="~/BacSi/DangNhap"><span class="text-primary">Chăm Sóc</span>-Sức Khỏe</a>

                @using (Html.BeginForm("TimKiem", "BacSi", FormMethod.Get))
                {
                    <div class="input-group input-navbar">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="icon-addon1"><button type="submit" class="mai-search" style="background-color: Transparent; border: none"></button></span>
                        </div>
                        <input type="text" class="form-control" id="timkiem" name="timkiem" placeholder="Nhập Từ Khóa..." aria-label="Username" aria-describedby="icon-addon1">
                    </div>
                }

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupport" aria-controls="navbarSupport" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupport">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="~/BacSi/TrangChuBS">Trang Chủ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="~/BenhAn/DSBenhAn">Hồ Sơ Bệnh Án</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="~/BacSi/LichHenBS/@userAdmin.MaBacSi" />Lịch Hẹn</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="~/BacSi/Lich/@userAdmin.MaBacSi">Đặt Lịch Làm Việc</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="~/BacSi/ThongTin/@userAdmin.MaBacSi">Thông Tin Cá Nhân</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-primary ml-lg-3" href="~/Home/DangXuat">Đăng Xuất</a>
                        </li>
                    </ul>
                </div> <!-- .navbar-collapse -->
            </div> <!-- .container -->
        </nav>
    </header>
    @RenderBody()
    <footer class="page-footer">
        <div class="container">
            <div class="row px-md-3">
                <div class="col-sm-6 col-lg-3 py-3">
                    <h5>Giới Thiệu</h5>
                    <ul class="footer-menu">
                        <li><a href="#">Chúng Tôi Là Ai</a></li>
                    </ul>
                </div>
                <div class="col-sm-6 col-lg-3 py-3">
                    <h5>Tin Tức</h5>
                    <ul class="footer-menu">
                        <li><a href="#">Chủ Đề Về COVID-19</a></li>
                </div>
                <div class="col-sm-6 col-lg-3 py-3">
                    <h5>Đối Tác</h5>
                    <ul class="footer-menu">
                        <li><a href="#">Bệnh Viện Từ Dũ</a></li>
                    </ul>
                </div>
                <div class="col-sm-6 col-lg-3 py-3">
                    <h5>Liên Hệ</h5>
                    <p class="footer-link mt-2">475A Điện Biên Phủ, Phường 25, Bình Thạnh, Thành phố Hồ Chí Minh</p>
                    <a href="#" class="footer-link">0904804756</a>
                    <a href="#" class="footer-link">chamsocsuckhoe@temporary.net</a>

                    <h5 class="mt-3">Mạng Xã Hội</h5>
                    <div class="footer-sosmed mt-3">
                        <a href="#" target="_blank"><span class="mai-logo-facebook-f"></span></a>
                        <a href="#" target="_blank"><span class="mai-logo-twitter"></span></a>
                        <a href="#" target="_blank"><span class="mai-logo-google-plus-g"></span></a>
                        <a href="#" target="_blank"><span class="mai-logo-instagram"></span></a>
                    </div>
                </div>
            </div>

            <hr>

            <span>2021 Trung Tâm Chăm Sóc Sức Khỏe</span>
            <br />
            <span>475A Điện Biên Phủ, Phường 25, Bình Thạnh, Thành phố Hồ Chí Minh</span>
        </div>
    </footer>

    <script src="~/Public/LayoutHome/js/jquery-3.5.1.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Public/LayoutHome/js/bootstrap.bundle.min.js"></script>
    <script src="~/Public/LayoutHome/vendor/owl-carousel/js/owl.carousel.min.js"></script>
    <script src="~/Public/LayoutHome/vendor/wow/wow.min.js"></script>
    <script src="~/Public/LayoutHome/js/theme.js"></script>

</body>
</html>

DACN/Views/Shared/Home_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <meta name="copyright" content="MACode ID, https://macodeid.com/">

    <title>One Health</title>
    <link href="~/Public/LayoutHome/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Public/LayoutHome/css/maicons.css" rel="stylesheet" />
    <link href="~//Public/LayoutHome/css/theme.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Public/LayoutHome/css/maicons.css">

    <link rel="stylesheet" href="~/Public/LayoutHome/css/bootstrap.css">

    <link rel="stylesheet" href="~/Public/LayoutHome/vendor/owl-carousel/css/owl.carousel.css">

    <link rel="stylesheet" href="~/Public/LayoutHome/vendor/animate/animate.css">

    <link rel="stylesheet" href="~/Public/LayoutHome/css/theme.css">
</head>
@{
    var userAdmin = Session["userAdmin"] as DACN.Models.BenhNhan;
}
<body>
    <!-- Back to top button -->
    <div class="back-to-top"></div>

    <header>
        <div class="topbar">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 text-sm">
                        <div class="site-info">
                            <a href="#"><span class="mai-call text-primary"></span> +84 090 480 4756</a>
                            <span class="divider">|</span>
                            <a href="#"><span class="mai-mail text-primary"></span> chamsocsuckhoe@temporary.net</a>
                        </div>
                    </div>
                    <div class="col-sm-4 text-right text-sm">
                        <div class="social-mini-button">
                            <a href="#"><span class="mai-logo-facebook-f"></span></a>
                            <a href="#"><span class="mai-logo-twitter"></span></a>
                            <a href="#"><span class="mai-logo-dribbble"></span></a>
                            <a href="#"><span class="mai-logo-instagram"></span></a>
                        </div>
                    </div>
                </div> <!-- .row -->
            </div> <!-- .container -->
        </div> <!-- .topbar -->

        <nav class="navbar navbar-expand-lg navbar-light shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="~/BacSi/DangNhap"><span class="text-primary">Chăm Sóc</span>-Sức Khỏe</a>
                @using (Html.BeginForm("TimKiem", "Home", FormMethod.Get))
                {
                    <div class="input-group input-navbar">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="icon-addon1"><button type="submit" class="mai-search" style="background-color: Transparent; border: none"></button></span>
                        </div>
                        <input type="text" class="form-control" id="timkiem" name="timkiem" placeholder="Nhập Từ Khóa..." aria-label="Username" aria-describedby="icon-addon1">
                    </div>
                }
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupport" aria-controls="navbarSupport" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupport">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="~/Home/Index">Trang Chủ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="~/Home/BenhAn/@userAdmin.MaBenhNhan">Hồ Sơ Bệnh Án</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="~/Home/BacSi">Bác Sĩ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="~/Home/LichHen/@userAdmin.MaBenhNhan">Lich Hẹn</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="~/Home/ThongTin/@userAdmin.MaBenhNhan">Thông Tin Cá Nhân</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="~/Home/LienHe">Liên Hệ</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-primary ml-lg-3" href="~/Home/DangXuat">Đăng Xuất</a>
                        </li>
                    </ul>
                </div> <!-- .navbar-collapse -->
            </div> <!-- .container -->
        </nav>
    </header>
    @if (TempData["AlertMessage"] != null)
    {
        <div id="AlertBox" class="alert @TempData["AlertType"] hide">
            @TempData["AlertMessage"]
        </div>
    }
    @RenderBody()
    <footer class="page-footer">
        <div class="container">
            <div class="row px-md-3">
                <div class="col-sm-6 col-lg-3 py-3">
                    <h5>Giới Thiệu</h5>
                    <ul class="footer-menu">
                        <li><a href="#">Chúng Tôi Là Ai</a></li>
                    </ul>
                </div>
                <div class="col-sm-6 col-lg-3 py-3">
                    <h5>Tin Tức</h5>
                    <ul class="footer-menu">
                        <li><a href="https://www.gavi.org/covid19?gclid=Cj0KCQiA47GNBhDrARIsAKfZ2rAdPrjoTZyF6bqwAa0kXq9kWYgxV9Ed2zzapkFF5-EyZze01ZILqbEaAvBQEALw_wcB">Chủ Đề Về COVID-19</a></li>
                    </ul>
                </div>
                <div class="col-sm-6 col-lg-3 py-3">
                    <h5>Đối Tác</h5>
                    <ul class="footer-menu">
                        <li><a href="#">Bệnh Viện Từ Dũ</a></li>
                    </ul>
                </div>
                <div class="col-sm-6 col-lg-3 py-3">
                    <h5>Liên Hệ</h5>
                    <p class="footer-link mt-2">475A Điện Biên Phủ, Phường 25, Bình Thạnh, Thành phố Hồ Chí Minh</p>
                    <a href="#" class="footer-link">0904804756</a>
                    <a href="#" class="footer-link">chamsocsuckhoe@temporary.net</a>

                    <h5 class="mt-3">Mạng Xã Hội</h5>
                    <div class="footer-sosmed mt-3">
                        <a href="#" target="_blank"><span class="mai-logo-facebook-f"></span></a>
                        <a href="#" target="_blank"><span class="mai-logo-twitter"></span></a>
                        <a href="#" target="_blank"><span class="mai-logo-google-plus-g"></span></a>
                        <a href="#" target="_blank"><span class="mai-logo-instagram"></span></a>
                    </div>
                </div>
            </div>

            <hr>

            <span>2021 Trung Tâm Chăm Sóc Sức Khỏe</span>
            <br />
            <span>475A Điện Biên Phủ, Phường 25, Bình Thạnh, Thành phố Hồ Chí Minh</span>
        </div>
    </footer>

    <script src="~/Public/LayoutHome/js/jquery-3.5.1.min.js"></script>
    <script src="~/Public/LayoutHome/js/bootstrap.bundle.min.js"></script>
    <script src="~/Public/LayoutHome/vendor/owl-carousel/js/owl.carousel.min.js"></script>
    <script src="~/Public/LayoutHome/vendor/wow/wow.min.js"></script>
    <script src="~/Public/LayoutHome/js/theme.js"></script>
</body>
</html>

DACN/Views/Shared/LoginLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="~/Public/images/icons/favicon.ico" />
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Public/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Public/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Public/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Public/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Public/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Public/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/Public/css/main.css">
    <!--===============================================================================================-->
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <script src="~/Public/layoutAdmin/js/scripts.js"></script>
</body>
</html>